Repository Dan-Bam/IndiStraw-MSA-Server, pull requests merged in 2023-06, with the labels that each got.

#12 🔀 :: id 중복 검사 기능 추가
  account/src/main/kotlin/com/project/indistraw/account/application/common/error/exception/IndiStrawAccountException.kt
  account/src/main/kotlin/com/project/indistraw/account/application/common/error/handler/GlobalExceptionHandler.kt
  account/src/main/kotlin/com/project/indistraw/account/application/common/error/response/ErrorResponse.kt
  account/src/main/kotlin/com/project/indistraw/account/application/exception/AccountNotFoundException.kt
  account/src/main/kotlin/com/project/indistraw/account/application/exception/PasswordNotMatchException.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/input/CheckAccountIdUseCase.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/CheckAccountIdService.kt
  account/src/main/kotlin/com/project/indistraw/global/security/filter/ExceptionHandlerFilter.kt
  account/src/main/kotlin/com/project/indistraw/global/security/token/common/exception/InvalidTokenTypeException.kt
  account/src/test/kotlin/com/project/indistraw/service/CheckAccountIdServiceTest.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature, ✅ test

#13 🔀 :: 중복된 핸드폰 번호 검사 기능 추가
  account/src/main/kotlin/com/project/indistraw/account/application/exception/DuplicatedAccountIdException.kt
  account/src/main/kotlin/com/project/indistraw/account/application/exception/DuplicatedPhoneNumberException.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/input/CheckPhoneNumberUseCase.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/CheckPhoneNumberService.kt
  account/src/test/kotlin/com/project/indistraw/service/CheckPhoneNumberServiceTest.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature, ✅ test

#14 🔀 :: 인증번호 발송 기능 추가
  account/src/main/kotlin/com/project/indistraw/account/adapter/output/message/CoolSmsAdapter.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/output/message/properties/CoolSmsProperties.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/CommandAuthCodePersistenceAdapter.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/common/converter/AuthCodeConverter.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/entity/AuthCodeEntity.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/repository/AuthCodeRepository.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/input/SendAuthCodeUseCase.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/output/CommandAuthCodePort.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/output/SendMessagePort.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/SendAuthCodeService.kt
  account/src/main/kotlin/com/project/indistraw/account/domain/AuthCode.kt
  account/src/main/resources/application.yml
  account/src/test/kotlin/com/project/indistraw/service/SendAuthCodeServiceTest.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature, ✅ test

#20 🔀 :: 비밀번호 변경 기능 추가
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/AccountWebAdapter.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/request/UpdatePasswordRequest.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/input/UpdatePasswordUseCase.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/input/dto/UpdatePasswordDto.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/output/AccountSecurityPort.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/UpdatePasswordService.kt
  account/src/main/kotlin/com/project/indistraw/global/security/adapter/AccountSecurityAdapter.kt
  account/src/test/kotlin/com/project/indistraw/service/UpdatePasswordServiceTest.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature, ✅ test

#21 🔀 :: 프로필 수정 기능 추가
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/AccountWebAdapter.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/request/UpdateAccountProfileRequest.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/input/UpdateAccountProfileUseCase.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/input/dto/UpdateAccountProfileDto.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/UpdateAccountProfileService.kt
  account/src/main/kotlin/com/project/indistraw/global/security/config/SecurityConfig.kt
  account/src/test/kotlin/com/project/indistraw/service/UpdateAccountProfileServiceTest.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature, ✅ test

#22 🔀 :: 인증코드 검증 테스트코드 이벤트 정의 안된 이슈 해결
  account/src/test/kotlin/com/project/indistraw/service/VerifyAuthCodeServiceTest.kt
Labels: 1️⃣ Priority: High, 😈 버그 fix

#23 🔀 :: 클라우드 타입 배포 안되는 이슈 해결
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/converter/AccountDataConverter.kt
Labels: 1️⃣ Priority: High, 😈 버그 fix

#24 🔀 :: 프로필 조회 기능 추가
  account/src/main/kotlin/com/project/indistraw/account/application/port/input/AccountProfileDetailUseCase.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/input/dto/AccountProfileDetailDto.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/AccountProfileDetailService.kt
  account/src/test/kotlin/com/project/indistraw/service/AccountProfileDetailServiceTest.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature, ✅ test

#25 🔀 :: 프로필 조회 API 추가
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/AccountWebAdapter.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/converter/AccountDataConverter.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/response/AccountProfileDetailResponse.kt
Labels: 2️⃣ Priority: Medium

#26 🔀 :: 계정 탈퇴 기능 추가
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/AccountWebAdapter.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/input/AccountWithdrawUseCase.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/AccountWithdrawService.kt
  account/src/main/kotlin/com/project/indistraw/global/security/config/SecurityConfig.kt
  account/src/test/kotlin/com/project/indistraw/service/AccountWithdrawServiceTest.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature, ✅ test

#27 🔀 :: 비밀번호 변경 권한 이슈 해결
  account/src/main/kotlin/com/project/indistraw/global/security/config/SecurityConfig.kt
Labels: 1️⃣ Priority: High, 😈 버그 fix

#31 🔀 :: 인증코드 확인 요청 5번 초과시 예외처리 로직 추가
  account/src/main/kotlin/com/project/indistraw/IndistrawAccountApplication.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/output/message/CoolSmsAdapter.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/QueryAuthenticationPersistenceAdapter.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/common/converter/AuthenticationConverter.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/entity/AuthenticationEntity.kt
  account/src/main/kotlin/com/project/indistraw/account/application/common/error/ErrorCode.kt
  account/src/main/kotlin/com/project/indistraw/account/application/exception/TooManyAuthCodeRequestException.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/output/QueryAuthenticationPort.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/SendAuthCodeService.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/VerifyAuthCodeService.kt
  account/src/main/kotlin/com/project/indistraw/account/domain/Authentication.kt
  account/src/main/kotlin/com/project/indistraw/global/event/CreateAuthenticationEventHandler.kt
  account/src/main/kotlin/com/project/indistraw/global/event/DeleteAuthenticationEventHandler.kt
  account/src/test/kotlin/com/project/indistraw/service/SendAuthCodeServiceTest.kt
  account/src/test/kotlin/com/project/indistraw/service/VerifyAuthCodeServiceTest.kt
Labels: 1️⃣ Priority: High, ✨ Feature, ✅ test

#32 🔀 :: coolsms 메세지 발송 실패시 예외 추가
  account/src/main/kotlin/com/project/indistraw/account/adapter/output/message/CoolSmsAdapter.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/output/message/exception/MessageSendFailedException.kt
  account/src/main/kotlin/com/project/indistraw/account/application/common/error/ErrorCode.kt
Labels: 2️⃣ Priority: Medium, 🔨 코드 리팩터링

#34 🔀 :: PR Branch 수정
  .github/workflows/Django-CI.yml
  .github/workflows/Spring-CI.yml
Labels: 1️⃣ Priority: High, ✨ Feature

#35 🔀 :: 전화번호 검사 비밀번호 변경, 회원가입 구분 로직 추가
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/AuthWebAdapter.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/input/CheckPhoneNumberUseCase.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/CheckPhoneNumberService.kt
  account/src/main/kotlin/com/project/indistraw/global/security/config/SecurityConfig.kt
Labels: 1️⃣ Priority: High

#36 🔀 :: 비밀번호 변경할때 기존 비밀번호와 새 비밀번호가 같을시 예외처리
  account/src/main/kotlin/com/project/indistraw/account/application/common/enums/CheckPhoneNumberType.kt
  account/src/main/kotlin/com/project/indistraw/account/application/common/error/ErrorCode.kt
  account/src/main/kotlin/com/project/indistraw/account/application/exception/DuplicatedNewPasswordException.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/UpdatePasswordService.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#38 🔀 :: PASSWORD -> FIND_ACCOUNT 상수명 변경
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/AuthWebAdapter.kt
  account/src/main/kotlin/com/project/indistraw/account/application/common/enums/CheckPhoneNumberType.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/input/CheckPhoneNumberUseCase.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/CheckPhoneNumberService.kt
  account/src/test/kotlin/com/project/indistraw/service/CheckPhoneNumberServiceTest.kt
  account/src/test/kotlin/com/project/indistraw/service/UpdatePasswordServiceTest.kt
Labels: 2️⃣ Priority: Medium, ✅ test

#39 🔀 :: 주소 검색 html 추가
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/converter/AuthDataConverter.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/request/AddressRequest.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/request/SignUpRequest.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/common/converter/AccountConverter.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/entity/AccountEntity.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/entity/Address.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/input/dto/AddressDto.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/input/dto/SignUpDto.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/SignUpService.kt
  account/src/main/kotlin/com/project/indistraw/account/domain/Account.kt
  account/src/main/kotlin/com/project/indistraw/account/domain/Address.kt
  account/src/main/kotlin/com/project/indistraw/global/security/config/SecurityConfig.kt
  account/src/main/resources/static/roadSearch.html
Labels: 1️⃣ Priority: High, ✨ Feature

#40 🔀 :: Auth-ApiGateWay 프로젝트 세팅
  .github/workflows/Django-CI.yml
  .github/workflows/Spring-CI.yml
  auth-agw/HELP.md
  auth-agw/build.gradle.kts
  auth-agw/gradle/wrapper/gradle-wrapper.jar
  auth-agw/gradle/wrapper/gradle-wrapper.properties
  auth-agw/gradlew
  auth-agw/gradlew.bat
  auth-agw/settings.gradle.kts
  auth-agw/src/main/kotlin/com/project/indistraw/AuthAgwApplication.kt
  auth-agw/src/main/resources/application.properties
Labels: 2️⃣ Priority: Medium

#42 🔀 :: 로그아웃 기능 추가
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/AccountWebAdapter.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/CommandRefreshTokenPersistenceAdapter.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/input/LogoutAccountUseCase.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/output/CommandRefreshTokenPort.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/LogoutAccountService.kt
  account/src/test/kotlin/com/project/indistraw/service/LogoutAccountServiceTest.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature, ✅ test

#44 🔀 :: 인증 Gateway 추가
  .github/workflows/Django-CI.yml
  .github/workflows/Spring-CI.yml
  auth-agw/build.gradle.kts
  auth-agw/src/main/kotlin/com/project/indistraw/AuthAgwApplication.kt
  auth-agw/src/main/kotlin/com/project/indistraw/error/exception/IndiStrawAuthGatewayException.kt
  auth-agw/src/main/kotlin/com/project/indistraw/error/handler/JwtTokenExceptionHandler.kt
  auth-agw/src/main/kotlin/com/project/indistraw/filter/JwtAuthenticationGatewayFilter.kt
  auth-agw/src/main/kotlin/com/project/indistraw/token/TokenParser.kt
  auth-agw/src/main/kotlin/com/project/indistraw/token/common/exception/InvalidTokenException.kt
  auth-agw/src/main/kotlin/com/project/indistraw/token/common/properties/JwtProperties.kt
  auth-agw/src/main/resources/application.properties
  auth-agw/src/main/resources/application.yml
Labels: 1️⃣ Priority: High, ✨ Feature

#45 🔀 :: Address, AddressDto 타입 추가
  account/src/test/kotlin/com/project/indistraw/common/AnyValueObjectGenerator.kt
Labels: 2️⃣ Priority: Medium, ✅ test

#46 :sparkles: :: logout endPoint 권한 추가
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/AccountWebAdapter.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/AuthWebAdapter.kt
  account/src/main/kotlin/com/project/indistraw/global/security/config/SecurityConfig.kt
Labels: 2️⃣ Priority: Medium

#47 🔀 :: Address 필드 nullable로 수정
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/converter/AccountDataConverter.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/converter/AuthDataConverter.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/request/SignUpRequest.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/request/UpdateAccountProfileRequest.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/response/AccountProfileDetailResponse.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/common/converter/AccountConverter.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/entity/AccountEntity.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/input/dto/AccountProfileDetailDto.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/input/dto/SignUpDto.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/input/dto/UpdateAccountProfileDto.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/AccountProfileDetailService.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/SignUpService.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/UpdateAccountProfileService.kt
  account/src/main/kotlin/com/project/indistraw/account/domain/Account.kt
  account/src/main/kotlin/com/project/indistraw/global/security/config/SecurityConfig.kt
Labels: 2️⃣ Priority: Medium

#49 🔀 :: Address nullable true로 수정
  account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/entity/Address.kt
Labels: 1️⃣ Priority: High

#51 🔀 :: Address 필드 nullable 수정
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/converter/AccountDataConverter.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/request/AddressRequest.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/request/UpdateAccountProfileRequest.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/response/AccountProfileDetailResponse.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/input/dto/AccountProfileDetailDto.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/input/dto/AddressDto.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/input/dto/UpdateAccountProfileDto.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/AccountProfileDetailService.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/UpdateAccountProfileService.kt
  account/src/main/kotlin/com/project/indistraw/account/domain/Account.kt
  account/src/main/kotlin/com/project/indistraw/account/domain/Address.kt
Labels: 2️⃣ Priority: Medium

#52 🔀 :: Address 필드 nullable 수정
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/AccountWebAdapter.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/converter/AccountDataConverter.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/request/AddressRequest.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/request/UpdateAccountProfileRequest.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/entity/AccountEntity.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/input/dto/AddressDto.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/input/dto/UpdateAccountProfileDto.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/UpdateAccountProfileService.kt
Labels: 2️⃣ Priority: Medium

#53 🔀 :: Rest하게 api 수정
  account/src/main/kotlin/com/project/indistraw/global/security/config/SecurityConfig.kt
Labels: 2️⃣ Priority: Medium

#54 🔀 :: 전화번호 변경 기능 추가
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/AccountWebAdapter.kt
  account/src/main/kotlin/com/project/indistraw/account/application/common/enums/CheckPhoneNumberType.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/output/UpdatePhoneNumberUseCase.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/CheckPhoneNumberService.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/UpdatePhoneNumberService.kt
  account/src/main/kotlin/com/project/indistraw/global/event/DeleteAuthenticationEventHandler.kt
  account/src/main/kotlin/com/project/indistraw/global/security/config/SecurityConfig.kt
  account/src/test/kotlin/com/project/indistraw/service/UpdatePhoneNumberServiceTest.kt
Labels: 2️⃣ Priority: Medium

#56 🔀 :: 주소 null null로 오는 이슈 해결
  account/src/main/kotlin/com/project/indistraw/account/application/service/AccountProfileDetailService.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/SignUpService.kt
Labels: 2️⃣ Priority: Medium, 😈 버그 fix

#58 🔀 :: Spring-CI 스크립트 각 서버마다 실행
  .github/workflows/Spring-Account-CI.yml
  .github/workflows/Spring-Crowdfunding-CI.yml
Labels: 1️⃣ Priority: High

#59 🔀 :: jwt 만료시간 response json 포맷 추가
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/response/TokenResponse.kt
Labels: 1️⃣ Priority: High

#57 🔀 :: 크라우드 펀딩 프로젝트 세팅
  .github/workflows/Spring-CI.yml
  crowdfunding/HELP.md
  crowdfunding/build.gradle.kts
  crowdfunding/gradle/wrapper/gradle-wrapper.jar
  crowdfunding/gradle/wrapper/gradle-wrapper.properties
  crowdfunding/gradlew
  crowdfunding/gradlew.bat
  crowdfunding/settings.gradle.kts
  crowdfunding/src/main/kotlin/com/project/indistraw/IndiStrawCrowdfundingApplication.kt
  crowdfunding/src/main/resources/application.yml
Labels: 2️⃣ Priority: Medium, ✨ Feature

#62 🔀 :: 전화번호 수정 안되는 이슈 해결
  account/src/main/kotlin/com/project/indistraw/account/application/common/util/AuthenticationValidator.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/UpdatePhoneNumberService.kt
  account/src/test/kotlin/com/project/indistraw/service/UpdatePhoneNumberServiceTest.kt
Labels: 1️⃣ Priority: High

#61 🔀 :: 크라우드 펀딩 생성 기능 추가
  .github/workflows/Spring-Account-CI.yml
  .github/workflows/Spring-Crowdfunding-CI.yml
  crowdfunding/build.gradle.kts
  crowdfunding/src/main/kotlin/com/project/indistraw/IndiStrawCrowdfundingApplication.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/data/request/CreateCrowdfundingRequest.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/data/request/DateRequest.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/data/request/DirectorAccountRequest.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/data/request/RewordRequest.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/CommandCrowdfundingPersistenceAdapter.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/common/converter/CrowdfundingConverter.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/common/entity/BaseIdxEntity.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/entity/AmountEntity.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/entity/CrowdfundingEntity.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/entity/DateEntity.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/entity/DirectorAccountEntity.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/repository/CrowdfundingRepository.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/common/annotation/ServiceWithReadOnlyTransaction.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/common/annotation/ServiceWithTransaction.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/common/error/ErrorCode.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/common/error/exception/IndiStrawCrowdfundingException.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/common/error/handler/GlobalExceptionHandler.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/common/error/response/ErrorResponse.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/CreateCrowdfundingUseCase.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/dto/CreateCrowdfundingDto.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/dto/DateDto.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/dto/DirectorAccountDto.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/dto/RewordDto.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/output/AccountSecurityPort.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/output/CommandCrowdfundingPort.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/CreateCrowdfundingService.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/domain/Activity.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/domain/Amount.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/domain/Crowdfunding.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/domain/Date.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/domain/DirectorAccount.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/global/security/adapter/AccountSecurityAdapter.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/global/security/filter/AuthenticationFilter.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/global/security/token/TokenParser.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/global/security/token/common/property/JwtProperties.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#64 🔀 :: 안되는 테스트 코드 수정
  account/src/test/kotlin/com/project/indistraw/service/AccountProfileDetailServiceTest.kt
  account/src/test/kotlin/com/project/indistraw/service/UpdateAccountProfileServiceTest.kt
Labels: 1️⃣ Priority: High

#63 🔀 :: Spring-CI working directory 설정
  .github/workflows/Spring-Account-CI.yml
  .github/workflows/Spring-Crowdfunding-CI.yml
Labels: 2️⃣ Priority: Medium

#69 🔀 :: 리스트, 디테일 조회 기능 추가
  crowdfunding/build.gradle.kts
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/CrowdfundingWebAdapter.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/converter/CrowdfundingDataConverter.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/data/request/RewordRequest.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/data/response/CrowdfundingDetailResponse.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/CommandRewordPersistenceAdapter.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/QueryCrowdfundingPersistenceAdapter.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/QueryRewordPersistenceAdapter.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/common/converter/CrowdfundingConverter.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/common/converter/RewordConverter.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/entity/DateEntity.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/repository/CrowdfundingRepository.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/repository/RewordRepository.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/CrowdfundingDetailUseCase.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/CrowdfundingListUseCase.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/SearchCrowdfundingUseCase.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/dto/CrowdfundingDetailDto.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/dto/CrowdfundingListDto.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/dto/CrowdfundingPagingDto.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/dto/RewordDto.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/output/QueryCrowdfundingPort.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/output/QueryRewordPort.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/CreateCrowdfundingService.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/CrowdfundingDetailService.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/CrowdfundingListService.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/SearchCrowdfundingService.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/domain/Date.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#68 🔀 :: 크라우드 펀딩, 검색 서비스 gateway 추가
  auth-agw/src/main/resources/application.yml
Labels: 2️⃣ Priority: Medium, ✨ Feature

#72 🔀 :: accountIdx -> idx로 수정
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/converter/CrowdfundingDataConverter.kt
Labels: 1️⃣ Priority: High

#73 🔀 :: accountIdx -> idx로 수정
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/data/response/CrowdfundingDetailResponse.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/feign/client/data/AccountInfoDto.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/CrowdfundingDetailService.kt
Labels: 1️⃣ Priority: High

#74 🔀 :: 계정 생성, 삭제 publisher 추가
  account/build.gradle.kts
  account/src/main/kotlin/com/project/indistraw/IndistrawAccountApplication.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/input/AccountWebAdapter.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/common/entity/BaseIdxEntity.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/common/entity/BaseTimeEntity.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/common/entity/BaseUUIDEntity.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/entity/AccountEntity.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/output/publisher/CreateAccountPublishAdapter.kt
  account/src/main/kotlin/com/project/indistraw/account/adapter/output/publisher/DeleteAccountPublishAdapter.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/input/SignUpUseCase.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/output/CreateAccountPublishPort.kt
  account/src/main/kotlin/com/project/indistraw/account/application/port/output/DeleteAccountPublishPort.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/AccountWithdrawService.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/FindAccountIdService.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/ReissueTokenService.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/SendAuthCodeService.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/SignInService.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/SignUpService.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/UpdateAccountInfoService.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/UpdateAddressService.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/UpdatePasswordService.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/UpdatePhoneNumberService.kt
  account/src/main/kotlin/com/project/indistraw/account/application/service/VerifyAuthCodeService.kt
  account/src/main/kotlin/com/project/indistraw/account/domain/Account.kt
  account/src/main/kotlin/com/project/indistraw/global/event/account/CreateAccountPublishEvent.kt
  account/src/main/kotlin/com/project/indistraw/global/event/account/CreateAccountPublishEventHandler.kt
  account/src/main/kotlin/com/project/indistraw/global/event/account/DeleteAccountPublishEvent.kt
  account/src/main/kotlin/com/project/indistraw/global/event/account/DeleteAccountPublishEventHandler.kt
  account/src/main/kotlin/com/project/indistraw/global/event/authentication/CreateAuthenticationEvent.kt
  account/src/main/kotlin/com/project/indistraw/global/event/authentication/CreateAuthenticationEventHandler.kt
  account/src/main/kotlin/com/project/indistraw/global/event/authentication/DeleteAuthenticationEvent.kt
  account/src/main/kotlin/com/project/indistraw/global/event/authentication/DeleteAuthenticationEventHandler.kt
  account/src/main/kotlin/com/project/indistraw/global/event/authentication/SaveRefreshTokenEvent.kt
  account/src/main/kotlin/com/project/indistraw/global/event/authentication/SaveRefreshTokenEventHandler.kt
  account/src/main/kotlin/com/project/indistraw/global/security/config/SecurityConfig.kt
  account/src/main/kotlin/com/project/indistraw/thirdparty/rabbitmq/config/RabbitMQConfig.kt
  account/src/main/kotlin/com/project/indistraw/thirdparty/rabbitmq/publisher/RabbitMQCreateAccountPublisher.kt
  account/src/main/kotlin/com/project/indistraw/thirdparty/rabbitmq/publisher/RabbitMQDeleteAccountPublisher.kt
  account/src/main/resources/application.yml
  account/src/test/kotlin/com/project/indistraw/service/AccountWithdrawServiceTest.kt
  account/src/test/kotlin/com/project/indistraw/service/FindAccountIdServiceTest.kt
  account/src/test/kotlin/com/project/indistraw/service/ReissueTokenServiceTest.kt
  account/src/test/kotlin/com/project/indistraw/service/SendAuthCodeServiceTest.kt
  account/src/test/kotlin/com/project/indistraw/service/SignInServiceTest.kt
  account/src/test/kotlin/com/project/indistraw/service/SignUpServiceTest.kt
  account/src/test/kotlin/com/project/indistraw/service/UpdatePasswordServiceTest.kt
  account/src/test/kotlin/com/project/indistraw/service/UpdatePhoneNumberServiceTest.kt
  account/src/test/kotlin/com/project/indistraw/service/VerifyAuthCodeServiceTest.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature, 🔨 코드 리팩터링

#75 🔀 :: 401, 403, 404 처리 로직 추가
  account/src/main/kotlin/com/project/indistraw/global/security/config/SecurityConfig.kt
  account/src/main/kotlin/com/project/indistraw/global/security/handler/CustomAccessDeniedHandler.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#76 🔀 :: dto accountIdx로 수정
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/feign/client/data/AccountInfoDto.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/CrowdfundingDetailService.kt
Labels: 1️⃣ Priority: High

#79 🔀 :: 크라우드 펀딩 status 수정 기능 추가
  crowdfunding/build.gradle.kts
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/converter/CrowdfundingDataConverter.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/data/response/CrowdfundingDetailResponse.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/data/response/CrowdfundingListResponse.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/QueryCrowdfundingPersistenceAdapter.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/QueryRewordPersistenceAdapter.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/common/converter/CrowdfundingConverter.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/common/converter/RewordConverter.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/entity/CrowdfundingEntity.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/repository/CrowdfundingRepository.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/exception/CrowdfundingNotFoundException.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/UpdateCrowdfundingStatusUseCase.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/dto/CrowdfundingDetailDto.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/dto/CrowdfundingListDto.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/output/QueryCrowdfundingPort.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/CreateCrowdfundingService.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/CrowdfundingDetailService.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/CrowdfundingListService.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/PopularCrowdfundingListService.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/UpdateCrowdfundingStatusService.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/domain/Crowdfunding.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/domain/StatusType.kt
  crowdfunding/src/main/resources/application.yml
Labels: 2️⃣ Priority: Medium, ✨ Feature

#80 :sparkles: :: 자신이 작성한 크라우드 펀딩 리스트 조회 기능 추가
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/CrowdfundingWebAdapter.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/FindMyCrowdfundingListUseCase.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/FindMyCrowdfundingListService.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#78 🔀 :: auth-agw -> gateway 서버로 네이밍 변경
  auth-agw/settings.gradle.kts
  gateway/HELP.md
  gateway/build.gradle.kts
  gateway/gradle/wrapper/gradle-wrapper.jar
  gateway/gradle/wrapper/gradle-wrapper.properties
  gateway/gradlew
  gateway/gradlew.bat
  gateway/settings.gradle.kts
  gateway/src/main/kotlin/com/project/indistraw/GatewayApplication.kt
  gateway/src/main/kotlin/com/project/indistraw/error/exception/IndiStrawAuthGatewayException.kt
  gateway/src/main/kotlin/com/project/indistraw/error/handler/JwtTokenExceptionHandler.kt
  gateway/src/main/kotlin/com/project/indistraw/filter/JwtAuthenticationGatewayFilter.kt
  gateway/src/main/kotlin/com/project/indistraw/token/TokenParser.kt
  gateway/src/main/kotlin/com/project/indistraw/token/common/exception/InvalidTokenException.kt
  gateway/src/main/kotlin/com/project/indistraw/token/common/properties/JwtProperties.kt
  gateway/src/main/resources/application.yml
Labels: 2️⃣ Priority: Medium, 🔨 코드 리팩터링

#82 🔀 :: pageSize 필드 삭제
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/converter/CrowdfundingDataConverter.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/data/response/CrowdfundingPagingResponse.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/dto/CrowdfundingPagingDto.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/CrowdfundingListService.kt
Labels: 2️⃣ Priority: Medium

#84 🔀 :: 리워드 totalCount 추가
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/converter/CrowdfundingDataConverter.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/data/request/RewordRequest.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/common/converter/RewordConverter.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/entity/RewordEntity.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/common/util/CalculateAmountUtil.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/dto/RewordDto.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/CreateCrowdfundingService.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/CrowdfundingDetailService.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/domain/Reword.kt
  crowdfunding/src/main/kotlin/com/project/indistraw/global/event/QueryCrowdfundingEventHandler.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature
