Repository Dan-Bam/IndiStraw-MSA-Server, pull requests merged in 2023-05, with the labels that each got.

#4 :recycle: :: Auth -> Account 서버로 통합
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  account/HELP.md
  account/build.gradle.kts
  account/gradle/wrapper/gradle-wrapper.jar
  account/gradle/wrapper/gradle-wrapper.properties
  account/gradlew
  account/gradlew.bat
  account/settings.gradle.kts
  account/src/main/kotlin/com/indistraw/account/IndistrawAccountApplication.kt
  account/src/main/resources/application.yml
  account/src/test/kotlin/com/indistraw/account/IndistrawAccountApplicationTests.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#2 ✨ :: Movie CRUD 뼈대 완성
  movie/api/__init__.py
  movie/api/admin.py
  movie/api/apps.py
  movie/api/migrations/0001_initial.py
  movie/api/migrations/__init__.py
  movie/api/models.py
  movie/api/pagination.py
  movie/api/serializers.py
  movie/api/tests.py
  movie/api/urls.py
  movie/api/views.py
  movie/movie/settings.py
  movie/movie/urls.py
Labels: 1️⃣ Priority: High, ✨ Feature

#5 🔀 :: 회원가입, 로그인 기능 추가
  account/build.gradle.kts
  account/src/main/kotlin/com/indistraw/account/IndistrawAccountApplication.kt
  account/src/main/kotlin/com/indistraw/account/adapter/input/AuthWebAdapter.kt
  account/src/main/kotlin/com/indistraw/account/adapter/input/converter/AuthDataConverter.kt
  account/src/main/kotlin/com/indistraw/account/adapter/input/request/SignInRequest.kt
  account/src/main/kotlin/com/indistraw/account/adapter/input/request/SignUpRequest.kt
  account/src/main/kotlin/com/indistraw/account/adapter/input/response/TokenResponse.kt
  account/src/main/kotlin/com/indistraw/account/adapter/output/persistence/CommandAccountPersistenceAdapter.kt
  account/src/main/kotlin/com/indistraw/account/adapter/output/persistence/QueryAccountPersistenceAdapter.kt
  account/src/main/kotlin/com/indistraw/account/adapter/output/persistence/common/converter/AccountConverter.kt
  account/src/main/kotlin/com/indistraw/account/adapter/output/persistence/common/entity/BaseIdxEntity.kt
  account/src/main/kotlin/com/indistraw/account/adapter/output/persistence/common/entity/BaseTimeEntity.kt
  account/src/main/kotlin/com/indistraw/account/adapter/output/persistence/common/entity/BaseUUIDEntity.kt
  account/src/main/kotlin/com/indistraw/account/adapter/output/persistence/entity/AccountEntity.kt
  account/src/main/kotlin/com/indistraw/account/adapter/output/persistence/repository/AccountRepository.kt
  account/src/main/kotlin/com/indistraw/account/adapter/output/security/PasswordEncodeAdapter.kt
  account/src/main/kotlin/com/indistraw/account/adapter/output/security/config/FilterConfig.kt
  account/src/main/kotlin/com/indistraw/account/adapter/output/security/config/PasswordEncodeConfig.kt
  account/src/main/kotlin/com/indistraw/account/adapter/output/security/config/SecurityConfig.kt
  account/src/main/kotlin/com/indistraw/account/adapter/output/security/filter/ExceptionHandlerFilter.kt
  account/src/main/kotlin/com/indistraw/account/adapter/output/security/filter/JwtRequestFilter.kt
  account/src/main/kotlin/com/indistraw/account/adapter/output/security/handler/CustomAuthenticationEntryPoint.kt
  account/src/main/kotlin/com/indistraw/account/adapter/output/security/jwt/JwtGenerateAdapter.kt
  account/src/main/kotlin/com/indistraw/account/adapter/output/security/jwt/JwtParseAdapter.kt
  account/src/main/kotlin/com/indistraw/account/adapter/output/security/jwt/common/exception/InvalidTokenTypeException.kt
  account/src/main/kotlin/com/indistraw/account/adapter/output/security/jwt/common/properties/JwtExpTimeProperties.kt
  account/src/main/kotlin/com/indistraw/account/adapter/output/security/jwt/common/properties/JwtProperties.kt
  account/src/main/kotlin/com/indistraw/account/adapter/output/security/principal/AccountDetails.kt
  account/src/main/kotlin/com/indistraw/account/adapter/output/security/principal/AccountDetailsService.kt
  account/src/main/kotlin/com/indistraw/account/adapter/output/security/principal/AdminDetails.kt
  account/src/main/kotlin/com/indistraw/account/adapter/output/security/principal/AdminDetailsService.kt
  account/src/main/kotlin/com/indistraw/account/application/common/annotation/ServiceWithReadOnlyTransaction.kt
  account/src/main/kotlin/com/indistraw/account/application/common/annotation/ServiceWithTransaction.kt
  account/src/main/kotlin/com/indistraw/account/application/common/error/ErrorCode.kt
  account/src/main/kotlin/com/indistraw/account/application/common/error/exception/IndiStrawAccountException.kt
  account/src/main/kotlin/com/indistraw/account/application/common/error/handler/GlobalExceptionHandler.kt
  account/src/main/kotlin/com/indistraw/account/application/common/error/response/ErrorResponse.kt
  account/src/main/kotlin/com/indistraw/account/application/exception/AccountNotFoundException.kt
  account/src/main/kotlin/com/indistraw/account/application/exception/PasswordNotMatchException.kt
  account/src/main/kotlin/com/indistraw/account/application/port/input/SignInUseCase.kt
  account/src/main/kotlin/com/indistraw/account/application/port/input/SignUpUseCase.kt
  account/src/main/kotlin/com/indistraw/account/application/port/input/dto/SignInDto.kt
  account/src/main/kotlin/com/indistraw/account/application/port/input/dto/SignUpDto.kt
  account/src/main/kotlin/com/indistraw/account/application/port/output/CommandAccountPort.kt
  account/src/main/kotlin/com/indistraw/account/application/port/output/JwtGeneratePort.kt
  account/src/main/kotlin/com/indistraw/account/application/port/output/JwtParsePort.kt
  account/src/main/kotlin/com/indistraw/account/application/port/output/PasswordEncodePort.kt
  account/src/main/kotlin/com/indistraw/account/application/port/output/QueryAccountPort.kt
  account/src/main/kotlin/com/indistraw/account/application/port/output/dto/TokenDto.kt
  account/src/main/kotlin/com/indistraw/account/application/service/SignInService.kt
  account/src/main/kotlin/com/indistraw/account/application/service/SignUpService.kt
  account/src/main/kotlin/com/indistraw/account/domain/Account.kt
  account/src/main/kotlin/com/indistraw/account/domain/Authority.kt
  account/src/main/kotlin/com/indistraw/account/domain/RefreshToken.kt
  account/src/main/resources/application.yml
  account/src/test/kotlin/com/indistraw/account/IndistrawAccountApplicationTests.kt
  account/src/test/kotlin/com/indistraw/account/common/AnyValueObjectGenerator.kt
  account/src/test/kotlin/com/indistraw/account/service/SignInServiceTest.kt
  account/src/test/kotlin/com/indistraw/account/service/SignUpServiceTest.kt
Labels: 1️⃣ Priority: High, ✨ Feature, ✅ test

#6 🔀 :: mariaDB 의존성 추가
  account/build.gradle.kts
  account/src/main/resources/application.yml
Labels: 1️⃣ Priority: High, ✨ Feature

#7 🔀 :: name size 수정
  account/src/main/kotlin/com/indistraw/account/adapter/input/request/SignUpRequest.kt
Labels: 3️⃣ Priority: Low

#8 🔀 :: 정규표현식 안되는 이슈 해결
  account/src/main/kotlin/com/indistraw/account/adapter/input/request/SignUpRequest.kt
Labels: 1️⃣ Priority: High, 😈 버그 fix

#9 🔀 :: 특수문자 정규표현식 추가
  account/src/main/kotlin/com/indistraw/account/adapter/input/request/SignUpRequest.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#10 🔀 :: 로그인 특수문자 정규표현식 추가
  account/src/main/kotlin/com/indistraw/account/adapter/input/request/SignInRequest.kt
Labels: 2️⃣ Priority: Medium
